CREATE TABLE USERS
(
    USER_ID           NUMERIC UNIQUE NOT NULL,
    FIRST_NAME        VARCHAR(100),
    LAST_NAME         VARCHAR(100),
    EMAIL             VARCHAR(100),
    PASSWORD          VARCHAR(100),
    ANNUAL_LEAVE_DAYS NUMERIC,
    ROLE              VARCHAR(100),
    HIRE_DATE         DATE,
    DAYS_FROM_HIRE    NUMERIC,
    MANAGER_ID        NUMERIC,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE LEAVES
(
    LEAVE_ID       NUMERIC UNIQUE NOT NULL,
    LEAVE_REASON   VARCHAR(100),
    FROM_DATE      DATE,
    TO_DATE        DATE,
    NUMBER_OF_DAYS NUMERIC,
    STATUS         VARCHAR(100),
    USER_ID        NUMERIC,
    PRIMARY KEY (LEAVE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);